routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BukutamuCRUDController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('bukutamus', BukutamuCRUDController::class);

Route::get('/home', [BukutamuCRUDController::class, 'index'])->name('home');
Auth::routes();

Route::get('/', [BukutamuCRUDController::class, 'index'])->name('home');
Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Bukutamu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bukutamu extends Model
{
    use HasFactory;

    protected $primaryKey = 'nomor';
    protected $fillable = ['nama', 'email', 'komentar', 'foto'];

    public function tamuKategoris(){
        return $this->hasMany(TamuKategori::class, 'tamus_nomor', 'nomor');
    }

    public function hasKategoriByNomor($nomor){
        if($this->tamuKategoris->whereIn('kategoris_nomor', $nomor)->first()){
            return true;
        }
        
        return false;
    }
}

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;
}

app/Models/TamuKategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TamuKategori extends Model
{
    use HasFactory;

    protected $fillable = ['tamus_nomor', 'kategoris_nomor'];

    public function kategori(){
        return $this->hasOne(Kategori::class, 'nomor', 'kategoris_nomor');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BukutamuCRUDController.php
<?php
namespace App\Http\Controllers;
use App\Models\Bukutamu;
use App\Models\Kategori;
use App\Models\TamuKategori;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class bukutamuCRUDController extends Controller
{

//  Display a listing of the resource.

//  @return \Illuminate\Http\Response

    public function index()
    {
        $data['bukutamus'] = Bukutamu::orderBy('nomor','asc')->paginate(5);
        return view('bukutamus.index', $data);
    }

//  Show the form for creating a new resource.

//  @return \Illuminate\Http\Response

    public function create()
    {
        $kategoris = Kategori::get();
        $bukutamus = Bukutamu::get();
        return view('bukutamus.create', compact('bukutamus', 'kategoris'));
    }

// Store a newly created resource in storage.

// @param  \Illuminate\Http\Request  $request
// @return \Illuminate\Http\Response

    public function store(Request $request)
    {
        $request->validate([
        'nama' => 'required',
        'foto' => 'required|file|image',
        'email' => 'required|email:dns',
        'waktu' => 'required|date_format:Y-m-d H:i:s',
        'kategori' => 'required',
        'komentar' => 'required'
        ]);

        $path = Storage::disk('public')->putFile('foto', $request->file('foto'));

        $bukutamu = new Bukutamu;
        $bukutamu->nama = $request->nama;
        $bukutamu->foto = $path;
        $bukutamu->email = $request->email;
        $bukutamu->waktu = $request->waktu;
        $bukutamu->komentar = $request->komentar;
        $bukutamu->save();

        if ($request->has('kategori')) {
            foreach ($request['kategori'] as $kategoriNomor) {
                TamuKategori::create([
                    'tamus_nomor' => $bukutamu->nomor,
                    'kategoris_nomor' => (int) $kategoriNomor
                ]);
            }
        }

        return redirect()->route('bukutamus.index')
        ->with('success','Data tamu telah tersimpan.');
    }

// Display the specified resource.

// @param  \App\bukutamu  $bukutamu
// @return \Illuminate\Http\Response

    public function show(Bukutamu $bukutamu)
    {
        return view('bukutamus.show',compact('bukutamu'));
    } 

// Show the form for editing the specified resource.

// @param  \App\Bukutamu  $bukutamu
// @return \Illuminate\Http\Response

    public function edit(Bukutamu $bukutamu)
    {
        $kategoris = Kategori::get();
        $bukutamus = Bukutamu::get();
        return view('bukutamus.update',compact('bukutamu', 'kategoris', 'bukutamus'));
    }

// Update the specified resource in storage.

// @param  \Illuminate\Http\Request  $request
// @param  \App\bukutamu  $bukutamu
// @return \Illuminate\Http\Response

    public function update(Request $request, Bukutamu $bukutamu)
    {
        $request->validate([
        'nama' => 'required',
        'foto' => 'required|file|image',
        'email' => 'required|email:dns',
        'komentar' => 'required'
        ]);

        if($request->has('foto')){
            $path = Storage::disk('public')->putFile('foto', $request->file('foto'));
            $bukutamu->foto = $path;
        }

        $bukutamu->nama = $request['nama'];
        $bukutamu->email = $request['email'];
        $bukutamu->komentar = $request['komentar'];
        $bukutamu->save();

        TamuKategori::where('tamus_nomor', $bukutamu->nomor)->delete();

        if ($request->has('kategori')) {
            foreach ($request['kategori'] as $kategoriNomor) {
                TamuKategori::create([
                    'tamus_nomor' => $bukutamu->nomor,
                    'kategoris_nomor' => (int) $kategoriNomor
                ]);
            }
        }

        return redirect()->route('bukutamus.index')
        ->with('success','Data tamu telah diubah.');
    }

// Remove the specified resource from storage.

// @param  \App\Bukutamu  $bukutamu
// @return \Illuminate\Http\Response

    public function destroy(Bukutamu $bukutamu)
    {   
        TamuKategori::where('tamus_nomor', $bukutamu->nomor)->delete();
        $bukutamu->delete();
        return redirect()->route('bukutamus.index')
        ->with('success','Data tamu telah dihapus.');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/bukutamus/create.blade.php
@extends('layouts.app')

@section('content')

@auth
    @if(session('status'))
        <div class="alert alert-success">{{ session('status') }}</div>
    @endif

    <!-- container -->
    <div class="container">
 
        <div class="page-header">
            <h1>Masukkan Data Tamu</h1>
        </div>

        @php
            date_default_timezone_set("Asia/Jakarta");
        @endphp

        <form action="{{ route('bukutamus.store') }}" enctype="multipart/form-data" method="POST">
            @csrf
            <table class='table table-hover table-responsive table-bordered'>
                <tr>
                    <td>Nama</td>
                    <td><input type='text' name='nama' class='form-control' /></td>
                </tr>
                @error('nama')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Foto</td>
                    <td><input type='file' name='foto' class='form-control' /></td>
                </tr>
                @error('foto')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Kategori</td>
                    <td>
                        @foreach ($kategoris as $kategori) 
                            <input type="checkbox" id="{{$kategori->nama}}" name="kategori[]" value="{{$kategori->nomor}}">
                            <label for="{{$kategori->nama}}"> {{$kategori->nama}}</label><br>
                        @endforeach
                    </td>
                </tr>
                @error('kategori')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Email</td>
                    <td><input type='email' name='email' class='form-control'/></td>
                </tr>
                @error('email')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Waktu</td>
                    <td><input type='datetime' name='waktu' class='form-control' value="{{ date('Y-m-d H:i:s') }}"/></td>
                </tr>
                @error('waktu')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Komentar</td>
                    <td><textarea name='komentar' class='form-control'></textarea></td>
                </tr>
                @error('komentar')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td></td>
                    <td>
                        <input type='submit' value='Simpan' class='btn btn-primary' />
                        <a href="{{ route('bukutamus.index') }}" class='btn btn-danger'>Kembali ke Buku Tamu</a>
                    </td>
                </tr>
            </table>
        </form>
    
    </div> <!-- end .container -->
@endauth
@endsection

resources/views/bukutamus/index.blade.php
    @extends('layouts.app')

    @section('content')

    <!-- container -->
    <div class="container">

        @auth
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    {{ $message }}
                </div>
            @endif

            <a class="btn btn-primary m-b-1em" href="{{ route('bukutamus.create') }}">Masukkan Data Tamu Baru</a>
        @endauth

        <table class="table table-hover table-responsive table-bordered">
            
            <tr>
                <th>Nomor</th>
                <th>Nama</th>
                <th>Foto</th>
                <th>Kategori</th>
                <th>Email</th>
                <th>Waktu</th>
                <th>Komentar</th>
                @auth
                <th>Aksi</th>
                @endauth
            </tr>

            @foreach ($bukutamus as $key => $bukutamu)
                <tr>
                    <th scope="row">{{ $bukutamus->firstItem() + $key }}</th>
                    <td>{{ $bukutamu->nama }}</td>
                    <td>
                        @if ($bukutamu->foto)
                            <img src="{{Storage::url($bukutamu->foto)}}" alt="foto" style="width: 200px; height:auto;">
                        @endif
                      </td>
                    <td>
                        @foreach ($bukutamu->tamuKategoris as $tamuKategori) 
                            {{ $tamuKategori->Kategori->nama }}<br>
                        @endforeach
                    </td>
                    <td>{{ $bukutamu->email }}</td>
                    <td>{{ $bukutamu->waktu }}</td>
                    <td>{{ $bukutamu->komentar }}</td>

                    @auth
                        <td>
                            <a class="btn btn-warning m-r-1em" href="{{ route('bukutamus.edit',$bukutamu->nomor) }}">Ubah</a>
                            <button type="button" data-bs-toggle="modal" data-bs-target="#deleteModal{{$bukutamu->nomor}}" class="btn btn-danger">Hapus</button>
                            
                            <div class="modal fade" id="deleteModal{{$bukutamu->nomor}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Hapus Data Tamu</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <form method="POST" action="{{ route('bukutamus.destroy',$bukutamu->nomor) }}">
                                            @csrf

                                            @method('DELETE')
                                            <div class="modal-body" style="height:100px; display:flex; align-items:center; justify-content:center;">
                                                <h5 class="text-center">Apakah anda yakin ingin menghapus data tamu ini?</h5>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Kembali</button>
                                                <button type="submit" class="btn btn-danger">Ya</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    @endauth
                </tr>
            @endforeach
        </table>
        {!! $bukutamus->links('vendor\pagination\bootstrap-5') !!}

    </div> <!-- end .container -->

@endsection

resources/views/bukutamus/update.blade.php
@extends('layouts.app')

@section('content')

@auth
    <!-- container -->
    <div class="container">
 
        <div class="page-header">
            <h1>Ubah Data Tamu</h1>
        </div>

        @if(session('status'))
            <div class="alert alert-success">{{ session('status') }}</div>
        @endif

        <form action="{{ route('bukutamus.update',$bukutamu->nomor) }}" enctype="multipart/form-data" method="POST">
            @csrf
            @method('PUT')
            <table class='table table-hover table-responsive table-bordered'>
                <tr>
                    <td>Nama</td>
                    <td><input type='text' name='nama' value="{{ $bukutamu->nama }}" class='form-control' /></td>
                </tr>
                @error('nama')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Foto</td>
                    <td><input type='file' name='foto' class='form-control' /></td>
                </tr>
                @error('foto')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Kategori</td>
                    <td>
                        @foreach ($kategoris as $kategori) 
                            <input type="checkbox" id="{{$kategori->nama}}" name="kategori[]" value="{{$kategori->nomor}}" {{$bukutamu->hasKategoriByNomor($kategori->nomor) ? 'checked' : ''}}>
                            <label for="{{$kategori->nama}}"> {{$kategori->nama}}</label><br>
                        @endforeach
                    </td>
                </tr>
                @error('kategori')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Email</td>
                    <td><input type='email' name='email' value="{{ $bukutamu->email }}" class='form-control'></input></td>
                </tr>
                @error('email')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Komentar</td>
                    <td><textarea name='komentar' class='form-control'>{{ $bukutamu->komentar }}</textarea></td>
                </tr>
                @error('komentar')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td></td>
                    <td>
                        <input type='submit' value='Simpan Perubahan' class='btn btn-primary' />
                        <a href="{{ route('bukutamus.index') }}" class='btn btn-danger'>Kembali ke Buku Tamu</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>

@endauth
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Buku Data Tamu</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- Custom CSS -->
    <style>
        .m-r-1em{ margin-right:1em; }
        .m-b-1em{ margin-bottom:1em; }
        .m-l-1em{ margin-left:1em; }
        .mt0{ margin-top:0; }
    </style>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Buku Data Tamu
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Masuk') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Daftar') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Keluar') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</body>
</html>